import type { CardDefinition } from "./types";

export const CARD_CATALOG: CardDefinition[] = [
  // IMPULSO
  {
    id: "impulso_sprint_descontrolado",
    name: "Sprint descontrolado",
    element: "impulso",
    cost: 2,
    rarity: "common",
    effects: [
      { type: "enemy_hp_pct", value: 6 },
      { type: "rhythm_add", value: 2 },
      { type: "stress_add", value: 6 },
      { type: "stress_add", value: 10 },
    ],
  },
  {
    id: "impulso_tiron_correa",
    name: "Tiron de correa",
    element: "impulso",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "enemy_hp_flat", value: 6 },
      { type: "stress_add", value: 6 },
      { type: "stress_reduce", value: 6 },
      { type: "note", text: "Si Estres > 50: +1 Ritmo" },
    ],
  },
  {
    id: "impulso_arranque_subito",
    name: "Arranque subdito",
    element: "impulso",
    cost: 0,
    rarity: "common",
    effects: [
      { type: "note", text: "Juega otra carta. -1 Energia siguiente turno" },
    ],
  },
  {
    id: "impulso_cruzar_sin_mirar",
    name: "Cruzar sin mirar",
    element: "impulso",
    cost: 2,
    rarity: "rare",
    effects: [
      { type: "skip_enemy_action" },
      { type: "confusion_add", value: 1 },
    ],
  },
  {
    id: "impulso_embalarse",
    name: "Embalarse",
    element: "impulso",
    cost: 3,
    rarity: "rare",
    effects: [
      { type: "enemy_hp_pct", value: 10 },
      { type: "rhythm_add", value: 3 },
      { type: "stress_add", value: 8 },
      { type: "note", text: "Si recibes dano este turno: dano x1.5" },
    ],
  },
  {
    id: "impulso_no_parar",
    name: "No parar quieto",
    element: "impulso",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "note", text: "Si no juegas CALMA: roba 1 carta" },
    ],
  },
  {
    id: "impulso_salir_corriendo",
    name: "Salir corriendo",
    element: "impulso",
    cost: 2,
    rarity: "epic",
    exhaust: true,
    effects: [
      { type: "enemy_hp_pct", value: 50 },
      { type: "stress_add", value: 15 },
    ],
  },

  // CALMA
  {
    id: "calma_sentarse_esperar",
    name: "Sentarse y esperar",
    element: "calma",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "enemy_hp_flat", value: 4 },
      { type: "stress_add", value: 3 },
      { type: "calm_add", value: 1 },
    ],
  },
  {
    id: "calma_rutina_conocida",
    name: "Rutina conocida",
    element: "calma",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "enemy_hp_flat", value: 4 },
      { type: "stress_add", value: 3 },
      { type: "note", text: "Este turno no generas Estres" },
    ],
  },
  {
    id: "calma_respiracion_lenta",
    name: "Respiracion lenta",
    element: "calma",
    cost: 2,
    rarity: "rare",
    effects: [
      { type: "enemy_hp_flat", value: 6 },
      { type: "stress_add", value: 5 },
      { type: "stress_reduce", value: 12 },
      { type: "confusion_remove", value: 1 },
    ],
  },
  {
    id: "calma_mirada_neutra",
    name: "Mirada neutra",
    element: "calma",
    cost: 0,
    rarity: "common",
    effects: [
      { type: "enemy_hp_flat", value: 4 },
      { type: "stress_add", value: 3 },
      { type: "repeat_enemy_last" },
    ],
  },
  {
    id: "calma_pararse_seco",
    name: "Pararse en seco",
    element: "calma",
    cost: 0,
    rarity: "common",
    effects: [
      { type: "note", text: "Cancela efectos de movimiento" },
      { type: "confusion_add", value: 1 },
    ],
  },
  {
    id: "calma_todo_control",
    name: "Todo bajo control",
    element: "calma",
    cost: 2,
    rarity: "rare",
    effects: [{ type: "damage_reduction_pct", value: 40 }],
  },
  {
    id: "calma_aguantar_tipo",
    name: "Aguantar el tipo",
    element: "calma",
    cost: 3,
    rarity: "epic",
    effects: [
      { type: "note", text: "Si sobrevives: cura 10 Animo" },
    ],
  },

  // CAOS
  {
    id: "caos_ladrido_seco",
    name: "Ladrido seco",
    element: "caos",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "skip_enemy_action" },
      { type: "confusion_add", value: 1 },
    ],
  },
  {
    id: "caos_zigzag",
    name: "Zig-zag",
    element: "caos",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "note", text: "50% evita ataque; si falla +8 Estres" },
    ],
  },
  {
    id: "caos_dar_vueltas",
    name: "Dar vueltas",
    element: "caos",
    cost: 0,
    rarity: "common",
    effects: [{ type: "draw_cards", value: 1 }],
  },
  {
    id: "caos_ladrar_nada",
    name: "Ladrar a la nada",
    element: "caos",
    cost: 0,
    rarity: "common",
    effects: [{ type: "note", text: "50% nada / 50% enemigo pierde turno" }],
  },
  {
    id: "caos_montar_pollo",
    name: "Montar un pollo",
    element: "caos",
    cost: 2,
    rarity: "rare",
    effects: [
      { type: "enemy_hp_pct", value: 8 },
      { type: "stress_add", value: 6 },
      { type: "apply_tag", tag: "caos_enemigo" },
    ],
  },
  {
    id: "caos_interrumpir_todo",
    name: "Interrumpir todo",
    element: "caos",
    cost: 3,
    rarity: "epic",
    exhaust: true,
    effects: [{ type: "skip_enemy_action" }],
  },
  {
    id: "caos_ruido_constante",
    name: "Ruido constante",
    element: "caos",
    cost: 1,
    rarity: "rare",
    effects: [
      { type: "note", text: "Ambos ganan +Estres por turno" },
    ],
  },

  // VINCULO
  {
    id: "vinculo_snack_rapido",
    name: "Snack rapido",
    element: "vinculo",
    cost: 1,
    rarity: "common",
    effects: [{ type: "heal_mood", value: 7 }],
  },
  {
    id: "vinculo_mirada_tierna",
    name: "Mirada tierna",
    element: "vinculo",
    cost: 0,
    rarity: "common",
    effects: [{ type: "damage_reduction_pct", value: 20 }],
  },
  {
    id: "vinculo_buscar_humano",
    name: "Buscar al humano",
    element: "vinculo",
    cost: 2,
    rarity: "rare",
    effects: [{ type: "skip_enemy_action" }],
  },
  {
    id: "vinculo_mimos_recordados",
    name: "Mimos recordados",
    element: "vinculo",
    cost: 2,
    rarity: "rare",
    consumable: true,
    effects: [
      { type: "heal_mood", value: 12 },
      { type: "stress_reduce", value: 8 },
    ],
  },
  {
    id: "vinculo_sentirse_seguro",
    name: "Sentirse seguro",
    element: "vinculo",
    cost: 1,
    rarity: "common",
    effects: [{ type: "note", text: "Convierte Estres en Calma (hasta 6)" }],
  },
  {
    id: "vinculo_no_esta_solo",
    name: "No estoy solo",
    element: "vinculo",
    cost: 3,
    rarity: "epic",
    effects: [{ type: "note", text: "Si tienes Calma: dano -50%" }],
  },
  {
    id: "vinculo_volver_casa",
    name: "Volver a casa",
    element: "vinculo",
    cost: 3,
    rarity: "epic",
    exhaust: true,
    effects: [{ type: "exit_combat" }],
  },

  // TERRITORIO
  {
    id: "territorio_marcar",
    name: "Marcar territorio",
    element: "territorio",
    cost: 1,
    rarity: "common",
    effects: [
      { type: "enemy_hp_flat", value: 6 },
      { type: "stress_add", value: 4 },
      { type: "note", text: "Reduce proximo efecto negativo 50%" },
    ],
  },
  {
    id: "territorio_plantarse",
    name: "Plantarse firme",
    element: "territorio",
    cost: 0,
    rarity: "common",
    effects: [{ type: "note", text: "Bloquea empujes y Ritmo enemigo" }],
  },
  {
    id: "territorio_mirada_fija",
    name: "Mirada fija",
    element: "territorio",
    cost: 1,
    rarity: "rare",
    effects: [{ type: "note", text: "Enemigo no usa CAOS este turno" }],
  },
  {
    id: "territorio_no_pasara",
    name: "No pasaras",
    element: "territorio",
    cost: 2,
    rarity: "rare",
    effects: [{ type: "note", text: "Cancela movimiento IMPULSO enemigo" }],
  },
  {
    id: "territorio_control_espacio",
    name: "Control del espacio",
    element: "territorio",
    cost: 2,
    rarity: "rare",
    effects: [{ type: "note", text: "El enemigo repite patron" }],
  },
  {
    id: "territorio_imponerse",
    name: "Imponerse",
    element: "territorio",
    cost: 3,
    rarity: "epic",
    effects: [
      { type: "enemy_hp_pct", value: 18 },
      { type: "stress_add", value: 10 },
      { type: "note", text: "Reduce HP enemigo segun Ritmo" },
    ],
  },
  {
    id: "territorio_mi_sitio",
    name: "Este es mi sitio",
    element: "territorio",
    cost: 1,
    rarity: "epic",
    effects: [
      { type: "damage_reduction_pct", value: 20 },
      { type: "note", text: "Estres +2/turno" },
    ],
  },
];
