import type { EnemyDeck } from "./types";

export const ENEMY_DECKS: EnemyDeck[] = [
  {
    id: "orden_publico",
    name: "Fuerzas de orden",
    elements: ["calma", "territorio"],
    pattern: "reactive",
    cards: [
      {
        id: "orden_mirada_fija",
        name: "Mirada fija",
        element: "territorio",
        effects: [{ type: "stress_add", value: 13 }],
        tag: "basic",
      },
      {
        id: "orden_orden_seca",
        name: "Orden seca",
        element: "calma",
        effects: [{ type: "apply_tag", tag: "presion" }],
        tag: "basic",
      },
      {
        id: "orden_paso_frente",
        name: "Paso al frente",
        element: "territorio",
        effects: [{ type: "note", text: "Si Ritmo > 1: +12 Estres" }],
        tag: "reactive",
      },
      {
        id: "orden_gestion_espacio",
        name: "Gestion del espacio",
        element: "calma",
        effects: [{ type: "note", text: "Reduce Ritmo de Buster en 1" }],
        tag: "basic",
      },
      {
        id: "orden_advertencia",
        name: "Advertencia clara",
        element: "territorio",
        effects: [{ type: "note", text: "Proximo Sprint: dano x1.5" }],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "orden_control_institucional",
        name: "Control institucional",
        element: "calma",
        effects: [{ type: "damage_reduction_pct", value: 40 }],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "orden_identidad",
        name: "Todo bajo control",
        element: "calma",
        effects: [{ type: "repeat_enemy_last" }],
        tag: "identity",
      },
      {
        id: "orden_antidisturbios",
        name: "Antidisturbios",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 6 },
          { type: "note", text: "Requiere Presion para ser mas fuerte" },
        ],
        cooldown: 2,
        tag: "strong",
      },
    ],
  },
  {
    id: "txikiteros",
    name: "Grupo de Txikiteros",
    elements: ["caos"],
    pattern: "weighted",
    cards: [
      {
        id: "txiki_risa",
        name: "Risa colectiva",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "50% +6 Estres / 50% -6 Estres" },
        ],
        tag: "basic",
      },
      {
        id: "txiki_cantico",
        name: "Cantico improvisado",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "confusion_add", value: 1 },
        ],
        tag: "basic",
      },
      {
        id: "txiki_palmada",
        name: "Palmada excesiva",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Si no juegas carta: +6 Estres" },
        ],
        tag: "reactive",
      },
      {
        id: "txiki_invitacion",
        name: "Invitacion absurda",
        element: "caos",
        effects: [
          { type: "stress_add", value: 1 },
          { type: "note", text: "Inserta carta basura en tu mazo" },
        ],
        tag: "basic",
      },
      {
        id: "txiki_descontrol",
        name: "Descontrol momentaneo",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Patrones aleatorios este turno" },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "txiki_una_mas",
        name: "Una mas y nos vamos",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "+2 Ritmo a ambos" },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "txiki_ambiente",
        name: "Ambiente cargado",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Estres +2/turno" },
        ],
        tag: "basic",
      },
      {
        id: "txiki_identidad",
        name: "Caos total",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Cancela tu ultima carta" },
        ],
        tag: "identity",
      },
      {
        id: "txiki_revolucion_festiva",
        name: "Revolucion festiva",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Contraataque ligero" },
        ],
        cooldown: 2,
        tag: "strong",
      },
    ],
  },
  {
    id: "ideologizado",
    name: "Ideologizado",
    elements: ["caos", "territorio"],
    pattern: "reactive",
    cards: [
      {
        id: "ideo_argumento",
        name: "Argumento circular",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "confusion_add", value: 1 },
        ],
        tag: "basic",
      },
      {
        id: "ideo_tono",
        name: "Sube el tono",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Si jugaste CAOS: +6 Estres" },
        ],
        tag: "reactive",
      },
      {
        id: "ideo_monologo",
        name: "Monologo largo",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Bloquea una carta" },
        ],
        tag: "basic",
      },
      {
        id: "ideo_reafirmacion",
        name: "Reafirmacion",
        element: "territorio",
        effects: [{ type: "damage_reduction_pct", value: 20 }],
        tag: "basic",
      },
      {
        id: "ideo_cambio_marco",
        name: "Cambio de marco",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Convierte CALMA en Confusion" },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "ideo_autoridad",
        name: "Autoridad moral",
        element: "territorio",
        effects: [{ type: "stress_add", value: 2 }],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "ideo_no_escucha",
        name: "No escucha",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Ignora tu ultima defensa" },
        ],
        tag: "basic",
      },
      {
        id: "ideo_identidad",
        name: "Saturacion discursiva",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Cada turno +1 Confusion" },
        ],
        tag: "identity",
      },
      {
        id: "ideo_propaganda_radical",
        name: "Propaganda radical",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "confusion_add", value: 1 },
          { type: "note", text: "Desgaste ideologico" },
        ],
        cooldown: 3,
        tag: "strong",
      },
    ],
  },
  {
    id: "mediatico",
    name: "Personaje mediatico",
    elements: ["vinculo", "caos"],
    pattern: "weighted",
    cards: [
      {
        id: "med_exposicion",
        name: "Exposicion constante",
        element: "caos",
        effects: [
          { type: "note", text: "Cambia reglas del turno" },
        ],
        tag: "basic",
      },
      {
        id: "med_momento_viral",
        name: "Momento viral",
        element: "vinculo",
        effects: [{ type: "note", text: "Inserta carta especial" }],
        tag: "basic",
      },
      {
        id: "med_guino",
        name: "Guino cercano",
        element: "vinculo",
        effects: [{ type: "damage_reduction_pct", value: 20 }],
        tag: "basic",
      },
      {
        id: "med_ruido",
        name: "Ruido mediatico",
        element: "caos",
        effects: [
          { type: "confusion_add", value: 1 },
          { type: "stress_add", value: 7 },
        ],
        tag: "basic",
      },
      {
        id: "med_cambio_foco",
        name: "Cambio de foco",
        element: "caos",
        effects: [
          { type: "stress_add", value: 5 },
          { type: "note", text: "Cancela tu proximo efecto" },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "med_feedback",
        name: "Feedback masivo",
        element: "caos",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Estres +/-10 aleatorio" },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "med_presencia",
        name: "Presencia omnipresente",
        element: "vinculo",
        effects: [
          { type: "note", text: "No puedes pasar turno" },
        ],
        tag: "basic",
      },
      {
        id: "med_identidad",
        name: "Esto no va de ti",
        element: "caos",
        effects: [
          { type: "stress_add", value: 5 },
          { type: "note", text: "El enemigo elige tu carta" },
        ],
        tag: "identity",
      },
      {
        id: "med_control_informativo",
        name: "Control informativo",
        element: "caos",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "confusion_add", value: 1 },
          { type: "note", text: "Desorganiza la estrategia" },
        ],
        cooldown: 2,
        tag: "strong",
      },
    ],
  },
  {
    id: "tpose",
    name: "T-Pose",
    elements: ["territorio"],
    pattern: "rotation",
    cards: [
      {
        id: "tpose_nada_1",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_2",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_3",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_4",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_5",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_6",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_nada_7",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "basic",
      },
      {
        id: "tpose_identidad",
        name: "Nada",
        element: "territorio",
        effects: [{ type: "note", text: "Nada" }],
        tag: "identity",
      },
      {
        id: "tpose_apoyo_infantil",
        name: "Apoyo infantil",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 3 },
          { type: "note", text: "Aplauso ingenuo" },
        ],
        cooldown: 2,
        tag: "strong",
      },
    ],
  },
  {
    id: "idea_fundacional",
    name: "La Idea Fundacional",
    elements: ["territorio", "calma"],
    pattern: "rotation",
    cards: [
      {
        id: "idea_herencia",
        name: "Herencia",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 1 },
          { type: "note", text: "Inserta carta heredada" },
        ],
        tag: "basic",
      },
      {
        id: "idea_marco",
        name: "Marco historico",
        element: "calma",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Cambia debilidades elementales" },
        ],
        tag: "basic",
      },
      {
        id: "idea_normalizacion",
        name: "Normalizacion",
        element: "calma",
        effects: [
          { type: "stress_add", value: 1 },
          { type: "note", text: "Convierte CAOS en CALMA" },
        ],
        tag: "basic",
      },
      {
        id: "idea_institucionalizar",
        name: "Institucionalizar",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "TERRITORIO +10% dano" },
        ],
        tag: "strong",
      },
      {
        id: "idea_contradiccion",
        name: "Contradiccion",
        element: "calma",
        effects: [
          { type: "stress_add", value: 2 },
          { type: "note", text: "Cancela tu ultima decision" },
        ],
        cooldown: 3,
        tag: "strong",
      },
      {
        id: "idea_peso",
        name: "Peso simbolico",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 5 },
        ],
        cooldown: 2,
        tag: "strong",
      },
      {
        id: "idea_reescritura",
        name: "Reescritura",
        element: "calma",
        effects: [
          { type: "stress_add", value: 1 },
          { type: "note", text: "Transforma una carta del mazo" },
        ],
        tag: "basic",
      },
      {
        id: "idea_identidad",
        name: "Esto no termina",
        element: "territorio",
        effects: [
          { type: "stress_add", value: 4 },
          { type: "note", text: "Inicia eleccion final" },
        ],
        tag: "identity",
      },
    ],
  },
];
